[package]
name = "macros"
version = "0.1.0"
authors = ["王先硚 <xianqiao.wang@upai.com>"]

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro_derive" }